# Install dependencies
before_script:
  - conda env create -f environment.yml -n gitlab-ci
  - conda activate gitlab-ci
  - pip install coverage nose pytest pytest-cov

# Install package
Install:
  script: python setup.py test

# Remove conda env
after_script:
  - conda remove -n gitlab-ci --all -y
