# Install dependencies
before_script:
  - conda env create -f environment.yml
  - conda activate shapepipe
  - pip install coverage nose pytest pytest-cov

# Install package
Install:
  script: python setup.py test
