# Install dependencies
before_script:
  - pip install -r requirements.txt
  - pip install -r requirements_git.txt
  - pip install coverage nose pytest pytest-cov

# Install package
Install:
  script: python setup.py test
