# Install dependencies
before_script:
  ## aio-aws tests require moto-server which requires docker to run batch jobs
  - docker info
  # NOTE: docker run does not exit!  It hangs the build at this point.
  #- docker run alpine:latest /bin/sh -c 'echo Hello Alpine'
  ##
  ## mock AWS credentials with no content
  - test -f ~/.aws/credentials && rm ~/.aws/credentials
  - export AWS_SECRET_ACCESS_KEY=dummy_AWS_SECRET_ACCESS_KEY
  - export AWS_ACCESS_KEY_ID=dummy_AWS_ACCESS_KEY_ID
  ##
  ## Install build dependencies and glibc for Miniconda3 (alpine doesn't use glibc)
  - apk add --update --no-cache bash ca-certificates curl git glib libstdc++ make sed wget
  - ls -al ./*
  - cp alpine/sgerrand.rsa.pub /etc/apk/keys/sgerrand.rsa.pub
  - apk add ./alpine/glibc-2.30-r0.apk
  - apk add ./alpine/glibc-bin-2.30-r0.apk
  - apk add --allow-untrusted ./alpine/glibc-i18n-2.30-r0.apk
  - export LANG=en_US.UTF-8
  - /usr/glibc-compat/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
  - /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc/usr/lib
  - echo "export LANG=$LANG" > /etc/profile.d/locale.sh
  ##
  ## Install Miniconda3 to install python 3.6
  - export PYTHONDONTWRITEBYTECODE=1
  - export CONDA_DIR=/opt/conda
  - mkdir -p ${CONDA_DIR}
  - chmod a+rwx /opt/conda
  - curl -L "https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh" -o miniconda3.sh
  - /bin/bash miniconda3.sh -f -b -p "$CONDA_DIR"
  # - CONDA_DIR="/opt/conda"
  # - mkdir -p "$CONDA_DIR"
  # - apk add --no-cache --virtual  .build-dependencies glib libstdc++ bash ca-certificates wget
  # - apk add ./alpine/glibc-2.30-r0.apk
  # - apk add ./alpine/glibc-bin-2.30-r0.apk
  # - apk add --allow-untrusted ./alpine/glibc-i18n-2.30-r0.apk
  # - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  # - bash miniconda.sh -f -b -p "$CONDA_DIR"
  - export PATH=$CONDA_DIR/bin:$PATH
  - conda list -n gitlab-ci || conda env create -f environment.yml -n gitlab-ci
  - conda activate gitlab-ci
  - pip install coverage nose pytest pytest-cov

# Install package
Install:
  script: python setup.py test

# Remove conda env
# after_script:
#   - conda remove -n gitlab-ci --all -y
