# Install dependencies
before_script:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $PWD/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda list -n gitlab-ci || conda env create -f environment.yml -n gitlab-ci
  - conda activate gitlab-ci
  - pip install coverage nose pytest pytest-cov

# Install package
Install:
  script: python setup.py test

# Remove conda env
# after_script:
#   - conda remove -n gitlab-ci --all -y
