# Install dependencies
before_script:
  - pip install coverage nose pytest pytest-cov pytest-codestyle
  - pip install -r requirements.txt
  - pip install -r requirements_git.txt

# Install package
Install:
  script: python setup.py test
