#! /bin/csh

set module2compile = (modules/slogger_package modules/sconfig_package modules/mpfx_package modules/mpfg_package modules/mpfg3_package \
                      modules/multifit_package modules/scdm_package modules/scatalog_package modules/pse_package \
		       modules/gfit_common_package modules/mkpsf_package) 
set install_dir = /dsm/cosmo02/sparseastro/Euclid/code/cea-epfl/ShapePipe-install #To change for each user. 
set cdir = `pwd`
foreach k ($module2compile)
 echo "process" $k
 cd $k
 python setup.py install --prefix=${install_dir}
 cd cdir
end
