#! /bin/csh

set module2compile = (modules/mask_package \
                      modules/mpfg_package \
                      modules/mpfx_package \
                      modules/ngmix_wrapper_package \
                      modules/PSFExRun_package \
                      modules/PSFExInterpolation_package \
                      modules/scatalog_package \
                      modules/sconfig_package \
                      modules/SExtractor_package \
                      modules/SETools_package \
                      modules/slogger_package \
                      modules/shapelens_package)

set install_option = $1
set cdir = `pwd`
foreach k ($module2compile)
 echo "process" $k
 cd $k
 if ($install_option == "") then
   python setup.py install
 else if ($install_option == "local") then
   python setup.py install --user
 else
   python setup.py install --prefix=$install_option
 endif
 cd cdir
end
