# Dockerfile for ShapePipe Jupyter Lab
# Uses the shared base image

FROM shapepipe-base

# Default command starts Jupyter Lab
ENTRYPOINT ["jupyter","lab","--ip=0.0.0.0","--port=8888","--no-browser","--allow-root"]
