# Dockerfile for ShapePipe Jupyter Lab
# Uses the shared base image

FROM ghcr.io/cosmostat/shapepipe:develop

# Default command starts Jupyter Lab
ENTRYPOINT ["jupyter","lab","--ip=0.0.0.0","--port=8888","--no-browser","--allow-root"]
