# ShapePipe Development Environment
# ---------------------------------
# This environment should only be used for development and testing of  
# ShapePipe (i.e. nothing that could be published). Packages need only
# specify the minimum compatible versions. This environment can updated 
# as needed.
name: shapepipe-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip>=21.2.4
  - astropy>=5.0
  - astromatic-source-extractor>=2.25.0
  - autoconf>=2.71
  - automake>=1.16
  - cmake>=3.27
  - galsim>=2.5
  - joblib>=1.3
  - libtool>=2.4
  - matplotlib>=3.8
  - numba>=0.57
  - numpy>=1.22
  - pandas>=2.1
  - pyqt5-sip>=12.12
  - pyqtgraph>=0.13
  - reproject>=0.12
  - sqlitedict>=2.1
  - termcolor>=2.3
  - tqdm>=4.66
  - treecorr>=4.3
  - wget
  - pip:
    - cs_util>=0.0.5
    - mccd>=1.2.3
    - modopt>=1.6
    - sip_tpv>=1.1
    - sf_tools>=2.0.4
    - python-pysap>=0.2.1
    - git+https://github.com/aguinot/ngmix@stable_version
    - git+https://github.com/tobias-liaudat/Stile@v0.1
