[project]
name = "shapepipe"
version = "1.1.0"
description = "Galaxy shape measurement pipeline."
readme = "README.rst"
authors = [
    { name = "Samuel Farrens", email = "samuel.farrens@cea.fr" },
    { name = "Axel Guinot", email = "axel.guinot@cea.fr" },
    { name = "Martin Kilbinger", email = "martin.kilbinger@cea.fr" }
]
license = { "file" = "LICENSE" }
requires-python = ">=3.12"
dependencies = [
    "joblib>=0.13",
    "modopt>=1.2",
    "numpy>=1.14",
    "pandas",
    "canfar",
    "sf_tools",
    "h5py",
    "healsparse",
    "skyproj",
]


[project.optional-dependencies]
doc = [
    "myst-parser",
    "numpydoc",
    "sphinx",
    "sphinxcontrib-bibtex",
    "sphinx-book-theme"
]
lint = [
    "black",
    "isort"
]
plot = [
    "skyproj",
    "matplotlib"
]
release = [
    "build",
    "twine",
]
test = [
    "pytest",
    "pytest-cov",
    "pytest-pycodestyle",
    "pytest-pydocstyle"
]
fitsio = ["fitsio"]
dev = ["shapepipe[doc,lint,release,test]"]

[project.scripts]
shapepipe_run = "shapepipe.shapepipe_run:main"
summary_run = "shapepipe.summary_run:main"
canfar_submit_job = "shapepipe.canfar_run:run_job"
canfar_monitor = "shapepipe.canfar_run:run_log"
canfar_monitor_log = "shapepipe.canfar_run:run_monitor_log"
get_ccd_with_psfs = "shapepipe.get_ccds_run:run_ccd_psf_handler"
download_headers = "shapepipe.coverage_run:run_download_headers"
extract_field_corners = "shapepipe.coverage_run:run_extract_corners"
build_coverage_map = "shapepipe.coverage_run:run_build_coverage"
plot_coverage_map = "shapepipe.coverage_run:run_plot_coverage"
coverage_pipeline = "shapepipe.coverage_run:run_pipeline"

[tool.pytest.ini_options]
addopts = "--verbose --cov=shapepipe"
testpaths = ["shapepipe"]
