# ShapePipe configuration file for fake PSF postage stamps (image simulations)


## Default ShapePipe options
[DEFAULT]

VERBOSE = True

RUN_NAME = run_sp_tile_fpsf

RUN_DATETIME = True


## ShapePipe execution options
[EXECUTION]

MODULE = fake_psf_runner

MODE = SMP


## ShapePipe file handling options
[FILE]

LOG_NAME = log_sp

RUN_LOG_NAME = log_run_sp

INPUT_DIR = $SP_RUN/output

OUTPUT_DIR = $SP_RUN/output


## ShapePipe job handling options
[JOB]

SMP_BATCH_SIZE = 1

TIMEOUT = 96:00:00


## Module options
[FAKE_PSF_RUNNER]

INPUT_MODULE = sextractor_runner

FILE_PATTERN = sexcat

FILE_EXT = .fits

NUMBERING_SCHEME = -000-000

# Path to the pickled PSF dictionary
PSF_DICT_PATH = /home/hervas/fhervas/workdir_skills/input/psf_files/Full_psf_dict.pickle
