name: Build API Doc

on: [workflow_dispatch]

jobs:

  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          auto-activate-base: true

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge pandoc
          python -m pip install --upgrade pip
          python -m pip install -r docs/requirements.txt
          python -m pip install .

      - name: Build API documentation
        shell: bash -l {0}
        run: |
          sphinx-apidoc -t docs/_templates -feTMo docs/source shapepipe
          sphinx-build -E docs/source docs/_build

      - name: Archive API build
        uses: actions/upload-artifact@v2
        with:
          name: api-docs
          retention-days: 14
          path: |
            docs/_build
