name: API Doc Test

on: [workflow_dispatch]

jobs:

  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          auto-activate-base: true

      - name: Install ShapePipe Python Package
        shell: bash -l {0}
        run: python -m pip install .

      - name: Build API documentation
        shell: bash -l {0}
        run: |
          sphinx-apidoc -t docs/_templates -feTMo docs/source shapepipe
          sphinx-build -E docs/source docs/_build

      - name: Archive API build
        uses: actions/upload-artifact@v2
        with:
          name: api-docs
          path: |
            docs/_build
