name: Build API Doc

on: [workflow_dispatch]

jobs:

  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
        with:
          auto-update-conda: true
          python-version: 3.8
          auto-activate-base: true

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          ./install_shapepipe --develop --no-exe --no-mpi
          conda activate shapepipe
          python -m pip install --upgrade importlib-metadata
          conda install -c conda-forge pandoc

      - name: Build API documentation
        shell: bash -l {0}
        run: |
          conda activate shapepipe
          sphinx-apidoc -t docs/_templates -feTMo docs/source shapepipe shapepipe/modules/*_runner.py
          sphinx-build -E docs/source docs/_build

      - name: Archive API build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: api-docs
          retention-days: 14
          path: |
            docs/_build
